version: '2'
services:
    codegen-app:
        image: codegen
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://codegen-postgresql:5432/codegen
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codegen-postgresql:
        extends:
            file: postgresql.yml
            service: codegen-postgresql
